---
# allow:
# - 93.184.216.34 # example.com
# - 185.60.219.6 # www.facebook.com
# - 185.60.219.16 # www.facebook.com
# - 185.60.219.35 # www.facebook.com
# - 185.60.219.38 # www.facebook.com
# deny:
# - 93.184.216.34 # example.com
# - 185.60.219.6 # www.facebook.com
# - 185.60.219.16 # www.facebook.com
# - 185.60.219.35 # www.facebook.com
# - 185.60.219.38 # www.facebook.com
# hostname: 0.0.0.0
# log: D:/temp
# port: 1080
# requiresUsernamePasswordAuthentication: true
# userNamePasswordPairs:
# - - admin
#   - 123456
# - - userName
#   - password